-- MySQL Script generated by MySQL Workbench
-- Wed May 22 15:04:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_fornecedor` (
  `id.fornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome_fornecedor` VARCHAR(45) NOT NULL,
  `CNPJ` INT(14) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `endereço_cep` INT(8) NOT NULL,
  `end_num` INT(5) NOT NULL,
  `end_bairro` VARCHAR(45) NOT NULL,
  `end__rua` VARCHAR(45) NOT NULL,
  `tel_comercial` INT(11) NOT NULL,
  `celular` INT(11) NOT NULL,
  PRIMARY KEY (`id.fornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(45) NOT NULL,
  `preco_custo` DECIMAL(8,2) NOT NULL,
  `preco_venda` DECIMAL(8,2) NOT NULL,
  `tamanho` CHAR(2) NOT NULL,
  `cor` CHAR(5) NOT NULL,
  `tb_produtocol` VARCHAR(45) NOT NULL,
  `tb_fornecedor_id.fornecedor` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_tb_produto_tb_fornecedor1_idx` (`tb_fornecedor_id.fornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_fornecedor`
    FOREIGN KEY (`tb_fornecedor_id.fornecedor`)
    REFERENCES `mydb`.`tb_fornecedor` (`id.fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compra`
-- -----------------------------------------------------"
CREATE TABLE IF NOT EXISTS `mydb`.`compra` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `preco_custo` DECIMAL(8,2) NOT NULL,
  `tb_fornecedor_id.fornecedor` INT NOT NULL,
  `data_compra` DATE NOT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_compra_tb_fornecedor_idx` (`tb_fornecedor_id.fornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_compra_tb_fornecedor`
    FOREIGN KEY (`tb_fornecedor_id.fornecedor`)
    REFERENCES `mydb`.`tb_fornecedor` (`id.fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `id_item` INT NOT NULL,
  `tb_produto_id_produto` INT NOT NULL,
  `compra_id_compra` INT NOT NULL,
  `quantidade_produto` INT NOT NULL,
  `preco_custo` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id_item`),
  INDEX `fk_item_tb_produto1_idx` (`tb_produto_id_produto` ASC) VISIBLE,
  INDEX `fk_item_compra1_idx` (`compra_id_compra` ASC) VISIBLE,
  CONSTRAINT `fk_item_tb_produto1`
    FOREIGN KEY (`tb_produto_id_produto`)
    REFERENCES `mydb`.`tb_produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_compra1`
    FOREIGN KEY (`compra_id_compra`)
    REFERENCES `mydb`.`compra` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
