-- MySQL Script generated by MySQL Workbench
-- Thu May 23 14:41:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema controledeestoque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controledeestoque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controledeestoque` DEFAULT CHARACTER SET utf8 ;
USE `controledeestoque` ;

-- -----------------------------------------------------
-- Table `controledeestoque`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledeestoque`.`usuario` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(75) NOT NULL,
  `email` VARCHAR(75) NOT NULL,
  `password` VARCHAR(75) NOT NULL,
  `dataregistro` DATE NOT NULL,
  `permissao` TINYINT NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledeestoque`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledeestoque`.`produto` (
  `codigorefprod` INT NOT NULL AUTO_INCREMENT,
  `nomeproduto` VARCHAR(75) NOT NULL,
  `usuario_iduser` INT NOT NULL,
  PRIMARY KEY (`codigorefprod`),
  INDEX `fk_produto_usuario_idx` (`usuario_iduser` ASC) ,
  CONSTRAINT `fk_produto_usuario`
    FOREIGN KEY (`usuario_iduser`)
    REFERENCES `controledeestoque`.`usuario` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledeestoque`.`fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledeestoque`.`fabricante` (
  `idfabricante` INT NOT NULL AUTO_INCREMENT,
  `nomefabricante` VARCHAR(75) NOT NULL,
  `CNPJfabricante` VARCHAR(16) NOT NULL,
  `emailfabricante` VARCHAR(75) NOT NULL,
  `telefonefabricante` VARCHAR(16) NOT NULL,
  `usuario_iduser` INT NOT NULL,
  PRIMARY KEY (`idfabricante`),
  INDEX `fk_fabricante_usuario1_idx` (`usuario_iduser` ASC) ,
  CONSTRAINT `fk_fabricante_usuario1`
    FOREIGN KEY (`usuario_iduser`)
    REFERENCES `controledeestoque`.`usuario` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledeestoque`.`representante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledeestoque`.`representante` (
  `idrepresentante` INT NOT NULL AUTO_INCREMENT,
  `nomerepresentante` VARCHAR(75) NOT NULL,
  `emailrepresentante` VARCHAR(45) NOT NULL,
  `telefonerepresentante` VARCHAR(16) NOT NULL,
  `fabricante_idfabricante` INT NOT NULL,
  `usuario_iduser` INT NOT NULL,
  PRIMARY KEY (`idrepresentante`),
  INDEX `fk_representante_fabricante1_idx` (`fabricante_idfabricante` ASC) ,
  INDEX `fk_representante_usuario1_idx` (`usuario_iduser` ASC) ,
  CONSTRAINT `fk_representante_fabricante1`
    FOREIGN KEY (`fabricante_idfabricante`)
    REFERENCES `controledeestoque`.`fabricante` (`idfabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_representante_usuario1`
    FOREIGN KEY (`usuario_iduser`)
    REFERENCES `controledeestoque`.`usuario` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledeestoque`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledeestoque`.`itens` (
  `iditens` INT NOT NULL AUTO_INCREMENT,
  `quantitens` DECIMAL(8,2) NOT NULL,
  `quantitensvend` DECIMAL(8,2) NOT NULL,
  `valcompitens` DECIMAL(8,2) NOT NULL,
  `valvenditens` DECIMAL(8,2) NOT NULL,
  `datacompraitens` DATE NOT NULL,
  `datavenda` DATE NULL,
  `ativo` TINYINT NOT NULL,
  `produto_codigorefprod` INT NOT NULL,
  `fabricante_idfabricante` INT NOT NULL,
  `usuario_iduser` INT NOT NULL,
  PRIMARY KEY (`iditens`),
  INDEX `fk_itens_produto1_idx` (`produto_codigorefprod` ASC) ,
  INDEX `fk_itens_fabricante1_idx` (`fabricante_idfabricante` ASC) ,
  INDEX `fk_itens_usuario1_idx` (`usuario_iduser` ASC) ,
  CONSTRAINT `fk_itens_produto1`
    FOREIGN KEY (`produto_codigorefprod`)
    REFERENCES `controledeestoque`.`produto` (`codigorefprod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_fabricante1`
    FOREIGN KEY (`fabricante_idfabricante`)
    REFERENCES `controledeestoque`.`fabricante` (`idfabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_usuario1`
    FOREIGN KEY (`usuario_iduser`)
    REFERENCES `controledeestoque`.`usuario` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
